# Generated by Django 3.2 on 2023-02-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_added_file_path_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('actor', 'actor'), ('director', 'director'), ('writer', 'writer')], null=True, verbose_name='role'),
        ),
    ]
